name: bootstrap_flutter
author: Gabriel Sávio <gbrlavio2@gmail.com>
version : 0.0.5
homepage : http://flutterando.com.br
description: The plugin create the ScaffoldWeb, and bootStrap organization Page

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: ^0.0.0
  flutter_web_ui: ^0.0.0 
dev_dependencies:
 # build_runner: ^1.4.0
  #build_web_compilers: ^2.0.0
 # pedantic: ^1.0.0

#dependency_overrides:
  #flutter_web:
   #git:
      #url: https://github.com/flutter/flutter_web
      #path: packages/flutter_web
  #flutter_web_ui:
    #git:
      #url: https://github.com/flutter/flutter_web
      #path: packages/flutter_web_ui
